### PR TITLE
Channel Points Support

### PR DESCRIPTION
**Pull request by BarRaider**
Added support for receiving events when Channel Points are redeemed

### CODE REVIEW

**Comment by JayJay1989** [comment]
is already in dev https://github.com/TwitchLib/TwitchLib.PubSub/pull/41

**Comment by sadmoody** [comment]
I stayed up until 4:30am last night putting together Channel Points support too. Was going to push it in through in a couple hours once everything was cleaned up. See my reaction - it was recorded.

https://clips.twitch.tv/ElatedPleasantCroissantPupper

Also please push #41 to master branch!

**Comment by BarRaider** [comment]
+1 please update the master branch, this is causing throwaway work from people who use this lib and want to contribute :-\

**Comment by JayJay1989** [comment]
> +1 please update the master branch, this is causing throwaway work from people who use this lib and want to contribute :-\

Indeed.

**Comment by Mahsaap** [comment]
sure, but keep in mind most if not all use dev for changes, Master normally doenst update very often. That being said it is in need to update and only Swift can do it. That I know of.

**Comment by Mahsaap** [comment]
Additionally when master changes it gets pushed to nuget, soooo this is why we use dev brand incase it breaks. Dev is also pushed to nuget like a nightly. given there is a change that day.

**Comment by BarRaider** [comment]
Totally understand and appreciate all the work..! Maybe updating the readme stating master is rarely updated (it's been 3 months) and to look at dev branch will help people who are less aware of what's the common practice on this repo...

**Comment by Mahsaap** [comment]
I have already added a small note to the readme in pr

**Pull request closed without merging**
