### PR TITLE
Channel Point Redemption Support

### PR DESCRIPTION
**Pull request by LonestarF1**
I tried to keep the formatting consistent with what I was seeing in other parts of the code, but if I missed the mark anywhere, I apologize.

Small update to PubSub that enables support for custom channel point reward redemption.

### CODE REVIEW

**Comment by JayJay1989** [comment]
This was already added.

**Comment by LonestarF1** [comment]
Oh gosh. I must've been blind as a bat! I was looking around a good bit too! Thanks!

**Comment by JayJay1989** [comment]
maybe merge it with my implementation in dev branch

**Comment by LonestarF1** [comment]
I'll take a gander and see if there's anything in mine that I'd like to see in yours. I didn't know about those undocumented topics, which is probably why I missed it! Very cool.

**Pull request closed without merging**
